# Generated by Django 3.2.7 on 2021-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ship', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('IP_Address', models.IntegerField()),
                ('Notes', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
